apiVersion: apps/v1
kind: Deployment
metadata:
  name: imitate-1k-0
  namespace: imitate
spec:
  selector:
    matchLabels:
      app: imitate-1k-0
  replicas: 1
  template:
    metadata:
      labels:
        app: imitate-1k-0
    spec:
      initContainers:
        - name: init-edge
          image: registry.cn-shanghai.aliyuncs.com/spliu/imitate-init:v1k-0.0.5

          # 挂载在所需要的目录
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
          command: [ 'cp', '-r' , '/work/quchao/EmulationFlow', '/cache/EmulationFlow' ]

      imagePullSecrets:
        - name: peking-image-secret
      containers:
        # 主进程
        - name: nginx
          image: registry.cn-shanghai.aliyuncs.com/k8smigu/nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /work/quchao
              name: cache-volume
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

        # 脚本运行
        - name: la
          image: registry.cn-shanghai.aliyuncs.com/k8smigu/nginx:latest
          workingDir: /work/quchao/EmulationFlow
          command: [ "/bin/sh" ]
          args: [ "-c", "/work/quchao/EmulationFlow/makeLive.sh" ]
          volumeMounts:
            - name: cache-volume
              mountPath: /work/quchao
          resources:
            limits:
              cpu: '0.1'
              memory: '4Gi'
            requests:
              cpu: '0.1'
              memory: '4Gi'
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 50Gi
        - name: nginx
          configMap:
            name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: imitate-1k-0
  namespace: imitate
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: imitate-1k-0
  type: NodePort